# Generated by Django 3.1.1 on 2021-10-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=120)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('biography', models.TextField()),
            ],
        ),
    ]
