# Generated by Django 3.1.1 on 2021-11-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=30)),
                ('cat_desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Our Team'},
        ),
        migrations.AlterField(
            model_name='team',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='Profile Picture'),
        ),
    ]
